Add development environment section to the readme
GeeksCAT/anem-per-feina-frontoffice pull request #33
Opened 2020-10-14 21:48 UTC by d-asensio

## Description

Adding recommendations for running the dev environment.

Not merge until #32 is merged

2020-10-14 22:06 UTC, XaviTorello requested changes
Perfect, just some typos :)

2020-10-14 22:06 UTC, XaviTorello commented on README.md
> +Use this if you are going to **integrate a feature** into the existing app, to do ti, run the following command:
"to do it"

2020-10-14 22:06 UTC, XaviTorello commented on README.md
> +> **Tip:** This step is going to be necessary every time that a dependency is updated by some contributos, so if you just updated your local copy of the project with the latest changes and something
"contributors", "missing"

2020-10-15 21:47 UTC, eudago approved these changes

2020-10-15 22:02 UTC, mcmontseny commented on README.md
> +yarn
No coneixia que yarn === yarn install. M'ho apunto! 👍

2020-10-16 15:59 UTC, XaviTorello approved these changes
Perfect!

2020-10-16 18:10 UTC, merged